"""Regenerate dev/popup.html and dev/options.html from the real pages in src/.

The dev copies point at ../src/* and load dev/chrome-shim.js first, so both
pages can be opened over http:// without installing the extension.

Usage:  python tools/make_dev_pages.py
"""
from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
BANNER = "<!-- GENERATED by tools/make_dev_pages.py - do not edit; run the script instead. -->\n"


def main() -> None:
    dev = ROOT / "dev"
    dev.mkdir(parents=True, exist_ok=True)
    for page in ("popup", "options"):
        html = (ROOT / "src" / f"{page}.html").read_text(encoding="utf-8")
        html = html.replace('href="ui.css"', 'href="../src/ui.css"')
        html = html.replace(f'href="{page}.css"', f'href="../src/{page}.css"')
        html = html.replace(
            f'<script type="module" src="{page}.js"></script>',
            '<script src="chrome-shim.js"></script>\n'
            f'  <script type="module" src="../src/{page}.js"></script>',
        )
        (dev / f"{page}.html").write_text(BANNER + html, encoding="utf-8")
        print(f"wrote dev/{page}.html")


if __name__ == "__main__":
    main()
